language: java

before_install:
  - chmod -R +x src
  - chmod +x gradlew
  - |
    echo "deb https://dl.bintray.com/sobolevn/deb git-secret main" | sudo tee -a /etc/apt/sources.list
    wget -qO - https://api.bintray.com/users/sobolevn/keys/gpg/public.key | sudo apt-key add -
    sudo apt-get update && sudo apt-get install git-secret

  - echo $GPG_PRIVATE_KEY | tr ',' '\n' > ./private_key.gpg

  - gpg --import ./private_key.gpg

  - git secret reveal -f

script: ./gradlew clean build

deploy:
  provider: script
  script: ./gradlew bintrayUpload -PbintrayUser=$bintray_user -PbintrayApiKey=$bintray_api_key
  on:
    branch: master
