language: java

before_install:
  - chmod -R +x src
  - chmod +x gradlew

script: ./gradlew clean build

deploy:
  provider: script
  script: ./gradlew bintrayUpload -PbintrayUser=$bintray_user -PbintrayApiKey=$bintray_api_key
  on:
    branch: master